version: '3'

services:

  app:
    build:
      context: ./docker/app
      dockerfile: rails_Dockerfile
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: dd6fbdb2807a6c7ab9baa4c281d4f491
    volumes:
      - .:/app
      - /var/tmp
      - bundle:/usr/local/bundle
      - sockets:/app/tmp/sockets
    depends_on:
      - db

  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_production
      MYSQL_USERNAME: root
    security_opt:
      - seccomp:unconfined
    ports:
      - "4306:3306"
    volumes:
      -  mysql_data:/var/lib/mysql

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: nginx_Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/log:/var/log/nginx
      - public-data:/app/public
      - sockets:/app/tmp/sockets
    depends_on:
      - app

volumes:
  bundle:
  mysql_data:
  public-data:
  sockets: